image: "crystallang/crystal:0.29.0"

spec & format:
  script:
  - shards install
  - crystal spec
  - crystal tool format --check

pages:
  stage: deploy
  script:
  - shards install
  - crystal docs -o public src/symm32.cr
  artifacts:
    paths:
    - public
  only:
  - master
